[Rainmeter]
Update=1000
AccurateText=1
DefaultAlwaysOnTop=-2
@include=#@#\WindowsColor.inc
@include2=#@#Settings.inc
@include3=#@#Layout.inc
@include4=#@#Overlay.inc
@include5=#@#ScrollBrightness.inc
@include6=#@#MovieMode.inc
MouseOverAction=[!ShowMeterGroup Percent] [!Redraw]
MouseLeaveAction=[!HideMeterGroup Percent] [!Redraw]
MouseScrollUpAction=[!EnableMeasure "BrightnessUp"] [!UpdateMeasure "BrightnessUp"]
MouseScrollDownAction=[!EnableMeasure "BrightnessDown"] [!UpdateMeasure "BrightnessDown"]

[Metadata]
Name=Brightness
Information=Monitor brightness widget - https://github.com/He11PC/rainmeter-brightness
Author=HellPC
Version=26.02.12
License=GPLv3

[Variables]
SavedBrightness=50
CurrentBrightness=#SavedBrightness#

;================================================================

[Monitor1_Brightness]
Measure=Calc
Formula=Round(#CurrentBrightness#*(#Monitor1_MaxBrightness#/100))
OnChangeAction=[!UpdateMeasure "Monitor1_SetBrightness"]
DynamicVariables=1
UpdateDivider=-1

[Monitor2_Brightness]
Measure=Calc
Formula=(Round(#CurrentBrightness#*(#Monitor2_MaxBrightness#/100)))*(1-#Movie_Mode#)
OnChangeAction=[!UpdateMeasure "Monitor2_SetBrightness"]
DynamicVariables=1
UpdateDivider=-1

[Monitor3_Brightness]
Measure=Calc
Formula=(Round(#CurrentBrightness#*(#Monitor3_MaxBrightness#/100)))*(1-#Movie_Mode#)
OnChangeAction=[!UpdateMeasure "Monitor3_SetBrightness"]
DynamicVariables=1
UpdateDivider=-1


[Monitor1_SetBrightness]
Measure=Plugin
Plugin=RunCommand
StartInFolder=ControlMyMonitor
Parameter=ControlMyMonitor.exe /SetValueIfNeeded "#Monitor1_Name#" 10 [Monitor1_Brightness]
OnUpdateAction=[!CommandMeasure Monitor1_SetBrightness "Run"]
FinishAction=[!Log "#Monitor1_Name# set to [Monitor1_Brightness]%" Notice]
State=Hide
DynamicVariables=1
UpdateDivider=-1

[Monitor2_SetBrightness]
Measure=Plugin
Plugin=RunCommand
StartInFolder=ControlMyMonitor
Parameter=ControlMyMonitor.exe /SetValueIfNeeded "#Monitor2_Name#" 10 [Monitor2_Brightness]
OnUpdateAction=[!CommandMeasure Monitor2_SetBrightness "Run"]
FinishAction=[!Log "#Monitor2_Name# set to [Monitor2_Brightness]%" Notice]
State=Hide
DynamicVariables=1
UpdateDivider=-1

[Monitor3_SetBrightness]
Measure=Plugin
Plugin=RunCommand
StartInFolder=ControlMyMonitor
Parameter=ControlMyMonitor.exe /SetValueIfNeeded "#Monitor3_Name#" 10 [Monitor3_Brightness]
OnUpdateAction=[!CommandMeasure Monitor3_SetBrightness "Run"]
FinishAction=[!Log "#Monitor3_Name# set to [Monitor3_Brightness]%" Notice]
State=Hide
DynamicVariables=1
UpdateDivider=-1

;================================================================

[SetBrightness]
Measure=Calc
Formula=#CurrentBrightness#
OnUpdateAction=[!UpdateMeasure "Monitor1_Brightness"] [!UpdateMeasure "Monitor2_Brightness"] [!UpdateMeasure "Monitor3_Brightness"] [!UpdateMeasure "Overlay_Alpha"]
DynamicVariables=1
UpdateDivider=-1
